#!/usr/bin/env bash
# script that configures a new Ubuntu machine and installs nginx on web-01
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx start
