#!/usr/bin/env bash
# script that configures a new Ubuntu machine and installs
# nginx on web-01

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
