#!/usr/bin/env bash
# script containing commands to automatically configure a Ubuntu machine
# to respect above requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
printf %s "server {
	listen 80;
	listen[::]:80 default_server;
	root /etc/nginx/html;
	location /redirect_me {
		return 301 http://cuberule.com/;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
