#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 53448-web-01 54.90.13.5:80 check\n\tserver 53448-web-02 18.207.139.113:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
