#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

#sudo apt-get -y install software-properties-common
#sudo add-apt-repository -y ppa:vbernat/haproxy-2.6

# Install HAProxy
sudo apt-get -y update
apt-get -y install haproxy

# Copy /etc/haproxy/haproxy.cfg to /etc/haproxy/haproxy.cfg.original_copy
#sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}

# edit config file
server_config=\
"
frontend  aniebue-frontend
	bind *:80
	mode http
	default_backend aniebue-backend
backend aniebue-backend
	balance roundrobin
	server 53448-web-01 54.90.13.5 check
	server 53448-web-02 18.207.139.113 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
