#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6

# Install HAProxy
apt-get -y update
apt-get -y install haproxy

sed -i -e "$aENABLED=1\n" /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind *:80\n\tbalance roundrobin\n\tserver 53448-web-01 54.90.13.5:80 add check\n\tserver 53448-web-02 18.207.139.113:80 add:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
